name: Build with OpenFOAM v2404
on:
  push:
    branches-ignore:
      - 'OpenFOAM*'
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
  pull_request:
    branches-ignore:
      - 'OpenFOAM*'
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-22.04
    container: precice/precice:nightly
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up OpenFOAM
      uses: gerlero/setup-openfoam@v1
      with:
        openfoam-version: 2406
    - name: Build OpenFOAM-preCICE adapter
      run: ./Allwmake
